### ISSUE TITLE
All: Change coordinate system

### ISSUE THREAD

**Issue by rwarnking** [rwarnking/pdf-games#37]
# Task

Switch from using cartesian coordinates (x,y) to matrix notation (n,m). This does apply to all files up to this point.

- https://stackoverflow.com/questions/25642532/opencv-pointx-y-represent-column-row-or-row-column

Do not forget the generating for loops:
```
\xintFor* #1 in {\xintSeq{0}{\fieldHeight-1}} \do {%
    \xintFor* #2 in {\xintSeq{0}{\fieldWidth-1}} \do {%
    }
}
```

# PDF list 

- [x] AsciiDonut
- [x] Ascii_mon
- [x] Chess
- [x] ConnectFour
- [x] Crossword puzzle
- [x] Dont break the ice
- [x] Game of Life
- [x] Match-three puzzle
- [x] Mau Mau
- [x] Memory
- [x] Minesweeper
- [x] Mühle
- [x] Particles
- [x] Peg solitaire / Solo Noble
- [x] Set
- [x] Sidescrollter
- [x] Sudoku
- [ ] Tetris
- [ ] Tictactoe

**Comment by rwarnking** [comment]
Done with multiple commits, for example: e8635d8593b0202768f2c0c6855657602162a55a
