### ISSUE TITLE
All: Fix automated blocksize calculation

### ISSUE THREAD

**Issue by rwarnking** [rwarnking/pdf-games#38]
Calculate the max width and height of a block (gui element) depending on the linewidth and the amount of blocks that should be shown. This is done in some fashion already but the calculation is most likely not correct/robust.

## TODO

- [x] AsciiDonut
- [x] Ascii_mon
- [x] Chess
- [x] ConnectFour
- [x] Crossword puzzle
- [x] Dont break the ice
- [x] Game of Life
- [x] Match-three puzzle
- [x] Mau Mau
- [x] Memory
- [x] Minesweeper
- [x] Mühle
- [x] Particles
- [x] Peg solitaire / Solo Noble
- [x] Set
- [x] Sidescrollter
- [x] Sudoku
- [x] Tetris
- [x] Tictactoe
