### ISSUE TITLE
All: Rename to match naming convention

### ISSUE THREAD

**Issue by rwarnking** [rwarnking/pdf-games#46]
# Task

Adjust all PDFs to match the [Naming Convention](https://github.com/rwarnking/pdf-games/wiki/Naming-Convention).
For example:
- Rename all occurances of field to cell.
- Rename all occurances of game field to board state.
- Rename all occurances of block(size) to cell?!

Also might want to check array creations for compatibility with:
`var array = Array.apply(null, Array(SIZE)).map(_ => VALUE);`

Remove:
`footexclude, headexclude` in the `documentclass`

# PDF list

- [x] AsciiDonut
- [x] Ascii_mon
- [x] Chess
- [x] ConnectFour
- [x] Crossword puzzle
- [x] Dont break the ice
- [x] Game of Life
- [x] Match-three puzzle
- [x] Mau Mau
- [x] Memory
- [x] Minesweeper
- [x] Mühle
- [x] Particles
- [ ] Peg solitaire / Solo Noble
- [x] Set
- [ ] Sidescrollter
- [ ] Sudoku
- [ ] Tetris
- [ ] Tictactoe

**Comment by rwarnking** [comment]
Done with multiple commits, for example: a13224663e0141f9bf829c45a364e0d3d4a3a5bd
