### ISSUE TITLE
All: Add .gif to each wiki

### ISSUE THREAD

**Issue by rwarnking** [rwarnking/pdf-games#64]
Add to each wiki page a gif of the game. Need to create and upload the gif and adjust the URL on the wiki page.

## TODO

- [x] AsciiDonut
- [x] Ascii_mon
- [x] Chess
- [x] ConnectFour
- [x] Crossword puzzle
- [x] Dont break the ice
- [x] Game of Life
- [x] Match-three puzzle
- [x] Mau Mau
- [x] Memory
- [x] Minesweeper
- [x] Mühle
- [x] Particles
- [x] Peg solitaire / Solo Noble
- [x] Set
- [x] Sidescrollter
- [x] Sudoku
- [x] Tetris
- [x] Tictactoe

**Comment by rwarnking** [comment]
Added all gifs with commit: 7aaa95ab6bf2f22605be253372db65ce3ab28bd8

**Comment by rwarnking** [comment]
Done with commit: bc975eb068c4c1a42d0b9ecc524a989fa8fb0dd0
